#!/bin/bash
# files=`git status|grep -e "modified" -e "new file"|sed "s/new file:\(.*\)/\1/g"|sed "s/modified:\(.*\)/\1/g"|cut -f 2`

# add されているファイル群を取得
# files=$(git diff --cached --name-status | awk '$1 != "D" { print $2 }')
# files=$(git diff-tree HEAD --name-only | awk "NR!=1 {print}")

# commint 後にcommitされたファイルたちを取得
# deleteされたファイルは除く
files=$(git diff-tree HEAD -r --diff-filter=d | awk "NR!=1 {print}" | awk '{print $6}')


EXECDIR=$( cd "$( dirname "$0" )" && pwd -P )


$EXECDIR/../../deploy/ansible/deploy.sh $files

